services:
  app:
    build: .
    image: pudinalazhar/go-monitor:latest
    container_name: go-monitor
    ports:
      - "8086:8086"
    restart: unless-stopped
    environment:
      - GIN_MODE=release